spring.application.name=mdr

api-key.brevo=<key>

# MongoDB Configuration
spring.mongodb.uri=mongodb+srv://mandalcommon_db_user:<pwd>@mdr.vvddfrs.mongodb.net/mdr?appName=mdr
spring.data.mongodb.database=mdr
logging.level.org.mongodb.driver=INFO